FROM fedora:latest

RUN dnf install -y \
    texlive-scheme-full \
    texlive-collection-fontsrecommended \
    texlive-collection-latexextra \
    texlive-chktex \
    texlive-fonts-extra \
    latexmk \
    texlive-latex \
    biber \
    texlive-schemabloc \
    texlive-multirow \
    texlive-wrapfig \
    texlive-biblatex-apa \
    texlive-pgfplots \
    texlive-adjustbox \
    texlive-environ

